services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=true
      - OPENAI_API_KEY=your_openai_api_key
      - NEWS_API_KEY=your_news_api_key
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
